services:
  db:
    container_name: db
    hostname: db
    image: postgres:alpine
    restart: always
    ports:
      - 5432:5432
    expose:
      - 5432
    env_file:
      - '.env'

  app:
    container_name: app
    build: .
#    restart: always
    ports:
      - 8000:80
    expose:
      - 8000
    env_file:
      - '.env'

    depends_on:
      - db

#networks:
#  default:
#    external: true
#    name: aspp_net