version: "3"

services:
  db:
    container_name: db
    image: postgres:alpine
    restart: always
    ports:
      - "5432:5432"
    expose:
      - 5432
    env_file:
      - .env
    networks:
      - agbm_net

  app:
    depends_on:
      - db
    links:
      - db:db
    networks:
      - agbm_net
    build: .
    ports:
      - "8000:80"
    expose:
      - 8000
    env_file:
      - .env

networks:
  agbm_net:
    driver: bridge
