version: "3"

services:
  db:
    container_name: db
    image: postgres:alpine
    restart: always
    ports:
      - "5432:5432"
    expose:
      - 5432
    env_file:
      - .env
    networks:
      - agbm_net

  app:
    depends_on:
      - db
      - redis
    links:
      - db:db
    networks:
      - agbm_net
    build: .
    ports:
      - "8000:80"
    expose:
      - 8000
    env_file:
      - .env
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0

  redis:
    image: redis:6-alpine
    expose:
      - 6379
    networks:
      - agbm_net

  worker:
    build: .
    command: ['celery', '--app=src.worker.celery_worker', 'worker', '-l', 'info']
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
      - app
    networks:
      - agbm_net
    expose:
      - 6379
      - 5555

  flower:
    image: mher/flower
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
      - worker
    networks:
      - agbm_net
    ports:
      - "5555:5555"
    expose:
      - 6379
      - 5555

  prometheus:
    image: prom/prometheus
    depends_on:
      - app
    ports :
      - "9090:9090"
    expose:
      - 9090
    networks:
      agbm_net:

  grafana:
    image: grafana/grafana
    env_file:
      - .env
    ports:
      - "3000:3000"
    expose:
      - 3000
    depends_on:
      - prometheus
    volumes:
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    networks:
      agbm_net:

networks:
  agbm_net:
    driver: bridge
