apiVersion: 1

deleteDatasources:
  - name: Prometheus
    orgId: 1

datasources:
- name: Prometheus
  orgId: 1
  type: prometheus
  url: http://prometheus:9090
  isDefault: true
  access: proxy
  editable: true
