name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  YA_SERVICE_KEY_ID: ${{secrets.YA_SERVICE_KEY_ID}}
  YA_SERVICE_KEY_TOKEN: ${{secrets.YA_SERVICE_KEY_TOKEN}}

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag fcm:$(date +%s)
