name: FastAPI CI/CD

on:
  push:
    branches:
      - master

jobs:

  deploy:
    name: Pre-Deploying
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: multiple command
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          sudo apt update
          sudo apt install apt-transport-https ca-certificates curl software-properties-common
          docker --version || curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
          docker ps || sudo add-apt-repository 'deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable'
          docker images || apt-cache policy docker-ce
          docker --help || sudo apt install docker-ce -y
          docker-compose --help || sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          docker-compose || sudo chmod +x /usr/local/bin/docker-compose
          sudo chmod 666 /var/run/docker.sock
          
  deploy_ssh:
    name: Deploying by SSH and Docker
    needs: deploy
    continue-on-error: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_YA_SERVICE_KEY_ID: ${{ secrets.YA_SERVICE_KEY_ID }}
          envkey_YA_SERVICE_KEY_TOKEN: ${{ secrets.YA_SERVICE_KEY_TOKEN }}
          envkey_GF_SECURITY_ADMIN_USER: ${{ secrets.GF_SECURITY_ADMIN_USER }}
          envkey_GF_SECURITY_ADMIN_PASSWORD: ${{ secrets.GF_SECURITY_ADMIN_PASSWORD }}
      
      - name: Clean up artifacts
        uses: appleboy/ssh-action@v0.1.8
        if: always()
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script_stop: true
          script: rm -rf ${{ github.event.repository.name }}      
      
      - name: Clone repository
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script_stop: true
          script: |
            git clone \
              -b ${{ github.ref_name }} \
              --depth=1 \
              --single-branch \
              https://github.com/dspetrenko/fcm.git
              
      - name: Re-run containers 
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script_stop: true
          script: |
           cd  ${{ github.event.repository.name }} |
           docker compose down |
           docker compose up --build --detach
      

